'\" t
.nr is_macos 0
.TH LIQUIDCTL 8 2023\-01\-08 "liquidctl" "System Manager's Manual"
.
.SH NAME
liquidctl \- monitor and control liquid coolers and other devices
.
.SH SYNOPSIS
.SY liquidctl
.RI [ options ]
.B list
.SY liquidctl
.RI [ options ]
.B initialize
.RB [ all ]
.SY liquidctl
.RI [ options ]
.B status
.SY liquidctl
.RI [ options ]
.B set
.I channel
.B speed
.RI ( temperature
.IR percentage )
\&.\|.\|.\&
.SY liquidctl
.RI [ options ]
.B set
.I channel
.B speed
.I percentage
.SY liquidctl
.RI [ options ]
.B set
.I channel
.B color
.I mode
.RI [ color
\&.\|.\|.\&]
.SY liquidctl
.B \-\-version
.SY liquidctl
.B \-\-help
.YS
.
.SH DESCRIPTION
\fBliquidctl\fR is a utility for overseeing and controlling some hardware
monitoring devices not yet supported at the kernel level.
.if !\n[is_macos]\{  Because \fBliquidctl\fR directly accesses the hardware devices, root
privileges are generally required, though this can be avoided with
appropriate udev rules.
.\}
.PP
\fBliquidctl list\fR outputs all compatible devices found on the system.  In
case more than one device is found, the desired one can be selected for later
invocations with \fB--match=\fIsubstring\fR, where \fIsubstring\fR matches part
of the desired device's description using a case insensitive comparison.
.PP
\fBliquidctl list \fI\-\-verbose\fR enables the display of additional
identifiers and addresses that can also be used to select specific devices.
These can be better suited for certain use cases, such as non-interactive
scripts.
.PP
\fBliquidctl initialize\fR prepares a device for later commands, and most
devices must be initialized after every boot or when resuming from a suspended
state.  Unless finer control is required, all devices can be initialized at
once with \fBliquidctl initialize all\fR.  Some devices may output some
information at this stage.
.PP
\fBliquidctl status\fR displays the status of all devices that match the
provided filtering options.
.PP
\fBliquidctl set \fIchannel\fB speed\fR allows the user to set fan and pump
speeds.  These, depending on the device, can be set to fixed duty values,
variable temperature\–duty curves, or both.
.PP
\fBliquidctl set \fIchannel\fB color\fR allows the user to configure and set
lighting modes.  Supported lighting modes and additional options vary by device
and are listed in later sections of this manual.  Each color can be specified
as:
.IP \(bu
hexadecimal RGB with or without prefix '0x': \fIff7f3f\fR;
.IP \(bu
decimal RGB triple, R,G,B ∊ [0, 255]: \fIrgb(255,127,63)\fR;
.IP \(bu
hue\-saturation\-value HSV triple, H ∊ [0, 360], S,V ∊ [0, 100]: \fIhsv(20,75,100)\fR;
.IP \(bu
hue\-saturation\-lightness HSL triple, H ∊ [0, 360], S,L ∊ [0, 100]: \fIhsl(20,100,62)\fR.
.PP
\fBliquidctl set \fIchannel\fB screen\fR allows the user to configure the LCD
screen integrated into some AIO models.
.
.if !\n[is_macos]\{
.PP
\fBliquidctl\fR automatically detects when a kernel driver is bound to the device
and, whenever possible, uses it instead of directly accessing the device.
Alternatively, direct access to the device can be forced with
\fI\-\-direct\-access\fP.
.
.\}
.SH OPTIONS
.
.SS Device selection options
Devices can be selected using one or more values taken from \fBlist \fI\-\-verbose\fP.
.TP
.BI \-m\  substring\fR,\ \fP \-\-match= substring
Filter devices by case insensitive substring of device description.
.TP
.BI \-n\  number\fR,\ \fP \-\-pick= number
Pick among many results for a given filter.
.TP
.BI \-\-vendor= id
Filter devices by hexadecimal vendor id.
.TP
.BI \-\-product= id
Filter devices by hexadecimal product id.
.TP
.BI \-\-release= number
Filter devices by hexadecimal release number.
.TP
.BI \-\-serial= number
Filter devices by serial number.
.TP
.BI \-\-bus= bus
Filter devices by bus.
.TP
.BI \-\-address= address
Filter devices by address in bus.
.TP
.BI \-\-usb\-port= port
Filter devices by USB port in bus.
.TP
.BI \-d\  index\fR,\ \fP \-\-device= index
(Deprecated), select device by listing index.
.
.SS Animation options
Some devices and animation modes support additional options.
.TP
.BI \-\-speed= value
Abstract animation speed (device/mode specific).
.TP
.BI \-\-time\-per\-color= value
Time to wait on each color (seconds).
.TP
.BI \-\-time\-off= value
Time to wait with the LED turned off (seconds).
.TP
.BI \-\-alert\-threshold= number
Threshold temperature for a visual alert (degrees Celsius).
.TP
.BI \-\-alert\-color= color
Color used by the visual high temperature alert.
.TP
.BI \-\-direction= string
If the pattern should move forward or backward.
.TP
.BI \-\-start\-led= number
The first led to start the effect at.
.TP
.BI \-\-maximum\-leds= number
The number of LED's the effect should apply to.
.
.SS Other options
.TP
.BI \-\-fan\-mode= channel:mode[,...]
Set the fan modes.
.TP
.B \-\-single\-12v\-ocp
Enable single rail +12V OCP.
.TP
.BI \-\-pump\-mode= mode
Set the pump mode.
.TP
.BI \-\-temperature\-sensor= number
The temperature sensor number for the Commander Pro.
.TP
.B \-\-legacy\-690lc
Use Asetek 690LC in legacy mode (old Krakens).
.TP
.B \-\-non\-volatile
Store on non\-volatile controller memory.
.TP
.B \-\-direct\-access
Directly access the device despite kernel drivers.
.TP
.BI \-\-unsafe= features
Comman-separated bleeding-edge features to enable.
.TP
.B \-v\fR, \fP\-\-verbose
Output additional information.
.TP
.B \-g\fR, \fP\-\-debug
Show debug information on \fIstderr\fR.
.TP
.B \-\-json
Output machine-readable JSON.  Only supported with
.BR list ,\  initialize \ and\  status .
.TP
.B \-\-version
Display the version number.
.TP
.B \-\-help
Show the embedded help.
.
.SH EXIT STATUS
1 if there was an error, 0 otherwise.
.
.SH ENVIRONMENT
If \fBLANG\fR is set to \fIC\fR, non-ASCII characters are escaped from the
output of \fB\-\-json\fR.
.
.SH FILES
.TP
.ie \n[is_macos]
.I ~/Library/Caches/liquidctl/*
.el
.IR $XDG_RUNTIME_DIR/liquidctl/* ,\  /var/run/liquidctl/* ,\  /tmp/liquidctl/*
Internal data used by some drivers.
.\" e.g. RuntimeStorage for Legacy690Lc and HydroPlatinum
.
.SH EXAMPLE
.SY liquidctl
.B list \-\-verbose
.SY liquidctl
.B initialize all
.SY liquidctl
.BI \-\-match\  kraken\  set\  pump\  speed\  90
.SY liquidctl
.BI \-\-product\  170e\  set\  led\  color\  fading
.I 350017 ff2608
.SY liquidctl
.B status
.YS
.
.SH DEVICE SPECIFICS
.
.SS Aquacomputer D5 Next
.SS Aquacomputer Farbwerk 360
.SS Aquacomputer Octo
.SS Aquacomputer Quadro
Cooling channels: (D5 Next): \fIfan\fR, \fIpump\fR; (Octo): \fIfan[1\-8]\fR; (Quadro:) \fIfan[1\-4]\fR; (Farbwerk 360:) not applicable.
.PP
Lighting channels: not yet supported.
.SS Corsair iCUE Elite Capellix H100i, H115i, H150i
.SS Corsair Commander Core
.SS Corsair Commander Core XT
.SS Corsair Commander ST
Cooling channels: \fIfans\fR, \fIfan[1\-6]\fR; (only non-XT/Elite Capellix:) \fIpump\fR.
.PP
Lighting channels: not yet supported.
.SS Corsair Commander Pro
.SS Corsair Lighting Node Pro
.SS Corsair Lighting Node Core
.SS Corsair Obsidian 1000D
Cooling channels (only Commander Pro and Obsidian 1000D): \fIsync\fR, \fIfan[1\-6]\fR.
.PP
Where the fan connection types can be set with
.BI \-\-fan\-mode= channel:mode[,...] ,
where the allowed modes are: \fIoff\fR, \fIdc\fR, \fIpwm\fR.
.PP
Lighting channels: (only Lighting Node Core:) \fIled\fR;
(only Commander Pro and Lighting Node Pro:) \fIsync\fR, \fIled[1\-2]\fR.
.TS
l c
---
l c .
Mode	#colors
\fIclear\fR	0
\fIoff\fR	0
\fIfixed\fR	1
\fIcolor_shift\fR	2
\fIcolor_pulse\fR	2
\fIcolor_wave\fR	2
\fIvisor\fR	2
\fIblink\fR	2
\fImarquee\fR	1
\fIsequential\fR	1
\fIrainbow\fR	0
\fIrainbow2\fR	0
.TE
.PP
When applicable the animation speed can be set with
.BI \-\-speed= value ,
where the allowed values are: \fIfast\fR, \fImedium\fR, \fIslow\fR.
.PP
The animation direction can be set with
.BI \-\-direction= value ,
where the allowed values are: \fIforward\fR or \fIbackward\fR.
.BI \-\-start\-led= number ,
the first LED that the lighting effect should be for.
.BI \-\-start\-led= number ,
the first LED that the lighting effect should be for.
.BI \-\-maximum\-led= number ,
the number of LEDs that the lighting effect should applied to.
.BI \-\-temperature\-sensor= number ,
The temperature sensor that should be used to control the fan curves, probe 1 by default.
.SS Corsair Hydro H80i GT, H100i GTX, H110i GTX
.SS Corsair Hydro H80i v2, H100i v2, H115i
.SS EVGA CLC 120 (CL12), 240, 280, 360
Cooling channels: \fIpump\fR, \fIfan\fR.
.PP
Lighting channels: \fIlogo\fR.
.TS
l c c
---
l c c .
Mode	#colors	notes
\fIrainbow\fR	0	only available on EVGA coolers
\fIfading\fR	2
\fIblinking\fR	1
\fIfixed\fR	1
\fIblackout\fR	0	no high-temperature alerts
.TE
.PP
The \fIrainbow\fR mode speed can be configured with
.BI \-\-speed= [1\(en6] .
The speed of the other modes is instead customized with
.B \-\-time\-per\-color
.RI ( fading\  and\  blinking )
and
.B \-\-time\-off
.RI ( blinking\  only).
.PP
All modes except
.I blackout
support a visual high-temperature alert configured with
.B \-\-alert\-threshold
and
.BR \-\-alert\-color .
.PP
All current settings can be saved on non\-volatile on\-board memory by passing
.B \-\-non\-volatile
to any write command.  However, since write\-cycles are limited, this option
should be used sparingly.
.
.SS Corsair H100i Pro, H115i Pro, H150i Pro
Cooling channels: \fIfan\fR, \fIfan[1\(en2]\fR; (only H150i Pro:) \fIfan3\fR.
.PP
Pump mode (\fBinitialize \-\-pump\-mode \fImode\fR): \fIquiet\fR,
\fIbalanced\fR (default), \fIperformance\fR.
.PP
Lighting channel: \fIlogo\fR.
.TS
l c
--
l c .
Mode	#colors
\fIalert\fR	3
\fIshift\fR	2\(en4
\fIpulse\fR	1\(en4
\fIblinking\fR	1\(en4
\fIfixed\fR	1
.TE
.
.SS Corsair Hydro H100i Platinum, H100i Platinum SE, H115i Platinum
.SS Corsair Hydro H60i Pro XT, H100i Pro XT, H115i Pro XT, H150i Pro XT
.SS Corsair Hydro H100i Elite RGB
Cooling channels: \fIfan\fR, \fIfan[1\(en2]\fR; (only H150i Pro XT:) \fIfan3\fR.
.PP
Pump mode (\fBinitialize \-\-pump\-mode \fImode\fR): \fIquiet\fR,
\fIbalanced\fR (default), \fIextreme\fR.
.PP
Lighting channels: \fIsync\fR, \fIled\fR.
.TS
l l c c c
-----
l l c c c .
Channel	Mode	#colors (Platinum)	#colors (Pro XT/Elite RGB)	#colors (Platinum SE)
\fIled\fR	\fIoff\fR	0	0	0
\fIled\fR	\fIfixed\fR	1	1	1
\fIled\fR	\fIsuper\-fixed\fR	24	16	48
.TE
.
.SS NZXT Kraken X40, X60
.SS NZXT Kraken X31, X41, X61
Supports the same modes and options as a Corsair Hydro H80i GT (or similar), but
requires \fB\-\-legacy\-690lc\fR to be passed on all invocations.
.
.SS NZXT Kraken M22
.SS NZXT Kraken X42, X52, X62, X72
Cooling channels (only X42, X52, X62, X72): \fIpump\fR, \fIfan\fR.
.PP
Lighting channels: \fIlogo\fR, \fIring\fR, \fIsync\fR.
.TS
l c c c
----
l c c c .
Mode	logo	ring	#colors
\fIoff\fR	yes	yes	0
\fIfixed\fR	yes	yes	1
\fIsuper\-fixed\fR	yes	yes	1\(en9
\fIfading\fR	yes	yes	2\(en8
\fIalternating\fR	no	yes	2
\fIbreathing\fR	yes	yes	1\(en8
\fIsuper\-breathing\fR	yes	yes	1\(en9
\fIpulse\fR	yes	yes	1\(en8
\fItai\-chi\fR	no	yes	2
\fIwater\-cooler\fR	no	yes	0
\fIloading\fR	no	yes	1
\fIwings\fR	no	yes	1
.TE
.PP
When applicable the animation speed can be set with
.BI \-\-speed= value ,
where the allowed values are: \fIslowest\fR, \fIslower\fR, \fInormal\fR,
\fIfaster\fR, \fIfastest\fR.
The animation direction can be set with
.BI \-\-direction= value ,
where the allowed values are: \fIforward\fR or \fIbackward\fR.
.
.SS NZXT Kraken X53, X63, X73
.SS NZXT Kraken Z53, Z63, Z73
Cooling channels: \fIpump\fR; (only Z53, Z63, Z73:) \fIfan\fR.
.PP
Lighting channels: \fIexternal\fR; (only X53, X63, X73:) \fIring\fR, \fIlogo\fR, \fIsync\fR.
.PP
LCD screens (only Z53, Z63, Z73): \fIlcd\fR.
.TS
l c
----
l c .
Mode	#colors
\fIoff\fR	0
\fIfixed\fR	1
\fIfading\fR	2\(en8
\fIsuper\-fixed\fR	1\(en40
\fIalternating\-[3\-6]\fR	1\(en2
\fIpulse\fR	1\(en8
\fIbreathing\fR	1\(en8
\fIsuper\-breathing\fR	1\(en40
\fIcandle\fR	1
\fIstarry\-night\fR	1
\fIloading\fR	1
\fItai\-chi\fR	1\(en2
\fIwater\-cooler\fR	2
\fIwings\fR	1
.TE
.PP
When applicable the animation speed can be set with
.BI \-\-speed= value ,
where the allowed values are: \fIslowest\fR, \fIslower\fR, \fInormal\fR,
\fIfaster\fR, \fIfastest\fR.
The animation direction can be set with
.BI \-\-direction= value ,
where the allowed values are: \fIforward\fR or \fIbackward\fR.
.
.SS Corsair HX750i, HX850i, HX1000i, HX1200i, HX1500i
.SS Corsair RM650i, RM750i, RM850i, RM1000i
Cooling channels: \fIfan\fR.
.PP
Lighting channels: none.
.PP
Setting a fixed fan speed changes the fan mode to software control.  To revert
back to hardware control, run \fBinitialize\fR again.
.PP
(Experimental feature) The +12V rails normally function in multiple-rail mode.
Single-rail mode can be selected by passing \fB\-\-single\-12v\-ocp\fR to
\fBinitialize\fR.  To revert back to multiple-rail mode, run \fBinitialize\fR
again without that flag.
.
.SS NZXT E500, E650, E850
Cooling channels: none (feature not supported yet).
.PP
Lighting channels: none.
.
.SS NZXT Grid+ V3
Cooling channels: \fIfan[1\(en6]\fR, \fIsync\fR.
.PP
Lighting channels: none.
.
.SS NZXT Smart Device (V1)
Cooling channels: \fIfan[1\(en3]\fR, \fIsync\fR.
.PP
Lighting channels: \fIled\fR.
.TS
l c
----
l c .
Mode	#colors
\fIoff\fR	0
\fIfixed\fR	1
\fIsuper\-fixed\fR	1\(en40
\fIfading\fR	2\(en8
\fIalternating\fR	2
\fIbreathing\fR	1\(en8
\fIsuper\-breathing\fR	1\(en40
\fIpulse\fR	1\(en8
\fIcandle\fR	1
\fIwings\fR	1
.TE
.PP
When applicable the animation speed can be set with
.BI \-\-speed= value ,
where the allowed values are: \fIslowest\fR, \fIslower\fR, \fInormal\fR,
\fIfaster\fR, \fIfastest\fR.
The animation direction can be set with
.BI \-\-direction= value ,
where the allowed values are: \fIforward\fR or \fIbackward\fR.
.
.SS NZXT Smart Device V2
.SS NZXT RGB & Fan Controller
.SS NZXT RGB & Fan Controller (3+6 channels)
.SS NZXT HUE 2
.SS NZXT HUE 2 Ambient
.SS NZXT H1 V2
Cooling channels (only Smart Device V2, RGB & Fan Controller and H1 V2):
\fIfan[1\(en3]\fR.
.PP
Lighting channels (all but H1 V2): \fIled[1\(en2]\fR, \fIsync\fR.
.PP
Additional lighting channels (HUE 2): \fIled[3\(en4]\fR.
.PP
Additional lighting channels (RGB & Fan Controller (3+6 channels)): \fIled[3\(en6]\fR.
.TS
l c
----
l c .
Mode	#colors
\fIoff\fR	0
\fIfixed\fR	1
\fIsuper\-fixed\fR	1\(en40
\fIfading\fR	2\(en8
\fIalternating\-[3\-6]\fR	2
\fIpulse\fR	1\(en8
\fIbreathing\fR	1\(en8
\fIsuper\-breathing\fR	1\(en40
\fIcandle\fR	1
\fIstarry\-night\fR	1
\fIwings\fR	1
.TE
.PP
When applicable the animation speed can be set with
.BI \-\-speed= value ,
where the allowed values are: \fIslowest\fR, \fIslower\fR, \fInormal\fR,
\fIfaster\fR, \fIfastest\fR.
The animation direction can be set with
.BI \-\-direction= value ,
where the allowed values are: \fIforward\fR or \fIbackward\fR.
.
.SS ASUS Strix GTX 1050 OC
.SS ASUS Strix GTX 1050 Ti OC
.SS ASUS Strix GTX 1060 6GB
.SS ASUS Strix GTX 1060 OC 6GB
.SS ASUS Strix GTX 1070
.SS ASUS Strix GTX 1070 OC
.SS ASUS Strix GTX 1070 Ti
.SS ASUS Strix GTX 1070 Ti Advanced
.SS ASUS Strix GTX 1080
.SS ASUS Strix GTX 1080 Advanced
.SS ASUS Strix GTX 1080 OC
.SS ASUS Strix GTX 1080 Ti
.SS ASUS Strix GTX 1080 Ti OC
.SS ASUS Strix GTX 1650 Super OC
.SS ASUS Strix GTX 1660 Super OC
.SS ASUS Strix GTX 1660 Ti OC
.SS ASUS Strix RTX 2060 Evo
.SS ASUS Strix RTX 2060 Evo OC
.SS ASUS Strix RTX 2060 OC
.SS ASUS Strix RTX 2060 Super
.SS ASUS Strix RTX 2060 Super Advanced
.SS ASUS Strix RTX 2060 Super Evo Advanced
.SS ASUS Strix RTX 2060 Super OC
.SS ASUS Strix RTX 2070
.SS ASUS Strix RTX 2070 Advanced
.SS ASUS Strix RTX 2070 OC
.SS ASUS Strix RTX 2070 Super Advanced
.SS ASUS Strix RTX 2070 Super OC
.SS ASUS Strix RTX 2080 OC
.SS ASUS Strix RTX 2080 Super Advanced
.SS ASUS Strix RTX 2080 Super OC
.SS ASUS Strix RTX 2080 Ti
.SS ASUS Strix RTX 2080 Ti OC
.SS ASUS TUF RTX 3060 Ti OC
Cooling channels: none.
.PP
Lighting channels: \fIled\fR.
.TS
l c
----
l c .
Mode	#colors
\fIoff\fR	0
\fIfixed\fR	1
\fIflash\fR	1
\fIbreathing\fR	1
\fIrainbow\fR	0
.TE
.
.SS Corsair Vengeance RGB
Cooling channels: none.
.PP
Lighting channels: \fIled\fR.
.TS
l c
----
l c .
Mode	#colors
\fIoff\fR	0
\fIfixed\fR	1
\fIbreathing\fR	1\(en7
\fIfading\fR	2\(en7
.TE
.PP
When applicable the animation speed can be set with
.BI \-\-speed= value ,
where the allowed values are: \fIslowest\fR, \fIslower\fR, \fInormal\fR,
\fIfaster\fR, \fIfastest\fR.
.
.SS ASUS Aura LED Controller
Cooling channels: none.
.PP
Lighting channels: \fIled[1\(en4]\fR, \fIsync\fR.
.TS
l c
----
l c .
Mode	#colors
\fIoff\fR	0
\fIstatic\fR	1
\fIbreathing\fR	1
\fIflashing\fR	1
\fIspectrum_cycle\fR	0
\fIrainbow\fR	0
\fIspectrum_cycle_breathing\fR	0
\fIchase_fade\fR	1
\fIspectrum_cycle_chase_fade\fR	0
\fIchase\fR	1
\fIspectrum_cycle_chase\fR	0
\fIspectrum_cycle_wave\fR	0
\fIchase_rainbow_pulse\fR	0
\fIrainbow_flicker\fR	0
\fIgentle_transition\fR	0
\fIwave_propagation\fR	0
\fIwave_propagation_pause\fR	0
\fIred_pulse\fR	0
.TE
.
.SS Gigabyte RGB Fusion 2.0 5702 Controller
.SS Gigabyte RGB Fusion 2.0 8297 Controller
Cooling channels: none.
.PP
Lighting channels: \fIled[1\(en8]\fR, \fIsync\fR.
.TS
l c
----
l c .
Mode	#colors
\fIoff\fR	0
\fIfixed\fR	1
\fIpulse\fR	1
\fI(double\-)?flash\fR	1
\fIcolor\-cycle\fR	0
.TE
.PP
When applicable the animation speed can be set with
.BI \-\-speed= value ,
where the allowed values are: \fIslowest\fR, \fIslower\fR, \fInormal\fR,
\fIfaster\fR, \fIfastest\fR, \fIludicrous\fR.
.
.SS EVGA GTX 1070 FTW
.SS EVGA GTX 1070 FTW DT Gaming
.SS EVGA GTX 1070 FTW Hybrid
.SS EVGA GTX 1070 Ti FTW2
.SS EVGA GTX 1080 FTW
Cooling channels: none.
.PP
Lighting channels: \fIled\fR.
.TS
l c
----
l c .
Mode	#colors
\fIoff\fR	0
\fIfixed\fR	1
\fIbreathing\fR	1
\fIrainbow\fR	0
.TE
.
.SH SEE ALSO
The complete documentation is available in
the project's sources and
.UR https://github.com/liquidctl/liquidctl
homepage
.UE .
