[tool.pytest.ini_options]
addopts = "--doctest-modules -ra"

[tool.black]
line-length = 100
target-version = ["py37"]
extend-exclude = '''
  /*
    Exclude old files, pending a future conversion.  By default, new files
    should *not* be excluded.

    To have all items start with |, this isn't a real comment; still, it
    shouldn't match any real path.
  */
  | (^/conftest\.py$)
  | (^/extra/contrib/fusion_rgb_cycle\.py$)
  | (^/extra/linux/generate-uaccess-udev-rules\.py$)
  | (^/extra/windows/LQiNFO\.py$)
  | (^/liquidctl/__init__\.py$)
  | (^/liquidctl/cli\.py$)
  | (^/liquidctl/driver/__init__\.py$)
  | (^/liquidctl/driver/asetek\.py$)
  | (^/liquidctl/driver/asetek_pro\.py$)
  | (^/liquidctl/driver/base\.py$)
  | (^/liquidctl/driver/commander_core\.py$)
  | (^/liquidctl/driver/commander_pro\.py$)
  | (^/liquidctl/driver/corsair_hid_psu\.py$)
  | (^/liquidctl/driver/ddr4\.py$)
  | (^/liquidctl/driver/hydro_platinum\.py$)
  | (^/liquidctl/driver/kraken2\.py$)
  | (^/liquidctl/driver/kraken3\.py$)
  | (^/liquidctl/driver/nvidia\.py$)
  | (^/liquidctl/driver/nzxt_epsu\.py$)
  | (^/liquidctl/driver/rgb_fusion2\.py$)
  | (^/liquidctl/driver/smart_device\.py$)
  | (^/liquidctl/driver/smbus\.py$)
  | (^/liquidctl/driver/usb\.py$)
  | (^/liquidctl/error\.py$)
  | (^/liquidctl/extraversion\.py$)
  | (^/liquidctl/keyval\.py$)
  | (^/liquidctl/pmbus\.py$)
  | (^/liquidctl/util\.py$)
  | (^/liquidctl/version\.py$)
  | (^/setup\.py$)
  | (^/tests/_testutils\.py$)
  | (^/tests/test_api\.py$)
  | (^/tests/test_asetek\.py$)
  | (^/tests/test_asetek_pro\.py$)
  | (^/tests/test_backward_compatibility_10\.py$)
  | (^/tests/test_backward_compatibility_11\.py$)
  | (^/tests/test_backward_compatibility_12\.py$)
  | (^/tests/test_backward_compatibility_13\.py$)
  | (^/tests/test_backward_compatibility_14\.py$)
  | (^/tests/test_backward_compatibility_15\.py$)
  | (^/tests/test_cli\.py$)
  | (^/tests/test_commander_core\.py$)
  | (^/tests/test_commander_pro\.py$)
  | (^/tests/test_corsair_hid_psu\.py$)
  | (^/tests/test_ddr4\.py$)
  | (^/tests/test_hidapi_device\.py$)
  | (^/tests/test_hydro_platinum\.py$)
  | (^/tests/test_keyval\.py$)
  | (^/tests/test_kraken2\.py$)
  | (^/tests/test_nvidia\.py$)
  | (^/tests/test_nzxt_epsu\.py$)
  | (^/tests/test_rgb_fusion2\.py$)
  | (^/tests/test_smart_device\.py$)
  | (^/tests/test_smbus\.py$)
  | (^/tests/test_usb\.py$)
'''
