#!/usr/bin/env python3
"""Enumerate all HID devices without opening them."""

try:
    # The hidapi package, depending on how it's compiled, exposes one or two
    # top level modules: hid and, optionally, hidraw.  When both are available,
    # hid will be a libusb-based fallback implementation, and we prefer hidraw.
    import hidraw as hid
except ModuleNotFoundError:
    import hid


def main():
    devices = hid.enumerate()

    for device in devices:
        vendor_id = device.get("vendor_id", 0)
        product_id = device.get("product_id", 0)
        path = device.get("path", b"").decode("utf-8", errors="ignore")

        print(f"VID:PID={vendor_id:04x}:{product_id:04x} Path='{path}'")


if __name__ == "__main__":
    main()
