name: Bug Report
description: Report an issue with existing supported devices.
labels: ["bug"]
body:
  - type: textarea
    id: observed-behavior
    attributes:
      label: Describe the bug
      description: Please start by describing the bug in as much detail as possible.
      placeholder: ex. "liquidctl fails to read the fan speed of the two attached fans"
    validations:
      required: true
  - type: textarea
    id: user-attempted-commands
    attributes:
      label: Output of commands you ran
      description: Now list which commands were executed, what was the expected behavior, and what was observed instead.
      placeholder: |
        <!-- An example code block:
        ```
        $ liquidctl list
        Device #0: Corsair Vengeance RGB DIMM2
        Device #1: Corsair Vengeance RGB DIMM4
        Device #2: NZXT Smart Device (V1)
        Device #3: NZXT Kraken X (X42, X52, X62 or X72)
        ```
        -->
    validations:
      required: true
  - type: textarea
    id: user-attempted-commands-with-debug
    attributes:
      label: Output of all relevant commands (with `--debug` flag)
      description: Re-run all commands attempted with the `--debug` flag, and include the complete output.
      placeholder: |
        <!-- An example code block:
        ```
        $ liquidctl list
        Device #0: Corsair Vengeance RGB DIMM2
        Device #1: Corsair Vengeance RGB DIMM4
        Device #2: NZXT Smart Device (V1)
        Device #3: NZXT Kraken X (X42, X52, X62 or X72)
        ```
        -->
    validations:
      required: true
  - type: input
    id: info-device
    attributes:
      label: Affected device
      description: Which device isn't functioning as expected?
      placeholder: e.g. Corsair Hydro H100i Pro XT
    validations:
      required: false
  - type: input
    id: info-os
    attributes:
      label: Operating system
      description: Which OS are you using?
      placeholder: e.g. Arch, macOS, Windows 10
    validations:
      required: true
  - type: input
    id: install-method
    attributes:
      label: Installation method
      description: How did you install liquidctl? If the install failed please indicate what methods you tried.
      placeholder: e.g. Official Arch Linux repository 
    validations:
      required: true
  - type: input
    id: info-version
    attributes:
      label: Version of liquidctl
      description: Output of `liquidctl --version` If the install failed, indicate the version you tried to install.
      placeholder: e.g. liquidctl v1.9.0 (Linux-5.16.16-arch1-1-x86_64-with-glibc2.35) 
    validations:
      required: true

