name: Bug report
description: Report a possible bug in liquidctl.
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there already an issue for this?
      description: Please search our open issues to see if one already exists for this.
      options:
      - label: There is no open issue for this
        required: true
  - type: checkboxes
    attributes:
      label: Is this a request for support of a new device?
      description: We are not currently taking new device. Please send a pull request instead.
      options:
      - label: This is not a new device request
        required: true
  - type: input
    id: affected-device
    attributes:
      label: Affected device
      description: Which device is affected by this bug?
      placeholder: e.g. Corsair Hydro H100i Pro XT
    validations:
      required: false
  - type: input
    id: liquidctl-version
    attributes:
      label: liquidctl version
      description: >
        What is the output from `liquidctl --version` or what version did you tried to install? If
        you are reporting an issue for a version other than the latest (currently 1.15.0), please
        first check that the problem has not already been fixed on the new version.
      placeholder: |
        e.g. liquidctl v1.15.0 (Linux-6.17.8-arch1-1-x86_64-with-glibc2.42)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Does the above version of liquidctl support the device in question?
      description: Please search our open issues to see if one already exists for this.
      description: >
        Please check the [Supported
        devices](https://github.com/liquidctl/liquidctl#supported-devices) section in the README to
        verify if your version has support. Support for new enough devices or features may have have
        made it to the liquidctl version you have, or may sometimes even require a recent Git
        snapshot.
      options:
      - label: The device is listead in the README as supported by my liquidctl version
        required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Please start by describing the bug in as much detail as possible. You can use
        [Markdown](https://docs.github.com/en/get-started/writing-on-github).
    validations:
      required: true
  - type: textarea
    id: commands-executed
    attributes:
      label: Commands executed
      description: >
        List the executed commands, and describe their expected behavior and what was observed
        instead. You can use Markdown, in particular [code
        blocks](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).
    validations:
      required: true
  - type: textarea
    id: commands-executed-with-debug
    attributes:
      label: Output of all relevant commands with `--debug` flag
      description: >
        Re-run all previous commands with the `--debug` flag, and include their complete output. You
        can use Markdown, in particular [code
        blocks](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).
    validations:
      required: true
  - type: input
    id: installation-method
    attributes:
      label: liquidctl installation method
      description: How did you install (or attempt to) liquidctl?
      placeholder: e.g. Official Arch Linux repository
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating system and version
      description: Which operating system and version are you using?
      placeholder: e.g. Windows 1125H2 or Arch Linux with kernel linux 6.17.8-arch1-1
    validations:
      required: true
