name: Bug report
description: Report a possible bug in liquidctl.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Please start by describing the bug in as much detail as possible. If a device is missing altogether, please check the [Supported devices](https://github.com/liquidctl/liquidctl#supported-devices) section in the README to verify that your version has support.
      placeholder: ex. "liquidctl fails to read the fan speed of the two attached fans"
    validations:
      required: true
  - type: textarea
    id: commands-executed
    attributes:
      label: Commands executed
      description: Now list which commands were executed, what was the expected behavior, and what was observed instead.
      placeholder: |
        <!-- An example code block: -->
        ```
        $ liquidctl status
        [ ... ]
        ```
    validations:
      required: true
  - type: textarea
    id: commands-executed-with-debug
    attributes:
      label: Output of all relevant commands with `--debug` flag
      description: Re-run all liquidctl commands with the `--debug` flag, and include the complete output.
      placeholder: |
        <!-- An example code block: -->
        ```
        $ liquidctl status --debug
        [ ... ]
        ```
    validations:
      required: true
  - type: input
    id: affected-device
    attributes:
      label: Affected device
      description: Which device isn't functioning as expected?
      placeholder: e.g. Corsair Hydro H100i Pro XT
    validations:
      required: false
  - type: dropdown
    id: checked-supported-devices
    attributes:
      label: Does your version of liquidctl support the device in question?
      description: Support for new enough devices can happen to be available only in Git snapshots for some time. Please check the [Supported devices](https://github.com/liquidctl/liquidctl#supported-devices) section in the README to verify if your version has support.
      options:
        - Yes, my version supports it
        - I've checked and it does not
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating system and version
      description: Which operating system are you using?
      placeholder: e.g. Arch Linux, mac OS, Windows 10
    validations:
      required: true
  - type: input
    id: installation-method
    attributes:
      label: Installation method
      description: How did you install liquidctl? If the installation failed, please indicate what methods you tried.
      placeholder: e.g. Official Arch Linux repository
    validations:
      required: true
  - type: input
    id: liquidctl-version
    attributes:
      label: Version of liquidctl
      description: What is the output from `liquidctl --version`? If the installation failed, use the version you tried to install. If you are reporting an issue for any liquidctl version other than the latest, please first check if the problem has not already been solved.
      placeholder: e.g. liquidctl v1.12.0.dev44+g12c1469909fd (Linux-6.0.10-arch2-1-x86_64-with-glibc2.36)
    validations:
      required: true

