name: Other questions
description: For all other questions / issues
labels: ["question"]
body:
  - type: textarea
    id: question-body
    attributes:
      label: Describe your question.
      description: Please provide any relevant information
    validations:
      required: true
