name: New Device Request
description: Request support for new devices.
labels: ["new device"]
body:
  - type: input
    id: info-device
    attributes:
      label: Device type
      description: What kind of device are you requesting support for?
      placeholder: e.g. AIO liquid cooler
    validations:
      required: true
  - type: input
    id: info-product-page
    attributes:
      label: Product page
      description: Please provide a link to the manufacture's product page for your exact device. 
      placeholder:  e.g. https://www.corsair.com/[...]
    validations:
      required: true
  - type: input
    id: software
    attributes:
      label: First-party software
      description: What software is provided by the manufacture to control the device?
      placeholder: e.g. Corsair iCue  
    validations:
      required: true
  - type: dropdown
    id: dropdown-monitoring
    attributes:
      label: What monitoring functionality does the device support?
      description: Select as many options as apply, not manditory.
      multiple: true
      options:
        - Temps
        - Fan/pump speeds or duty cycles
        - Voltages, currents or power
    validations:
      required: false
  - type: dropdown
    id: download-configure
    attributes:
      label: What configuration functionality does the device support?
      description: Select as many options as apply, not manditory.
      multiple: true
      options:
        - Fan/pump speeds
        - Voltages or current/power limits
        - Lighting of embedded LEDs
        - Lighting of accessories like RGB fans or LED strips
    validations:
      required: false
  - type: input
    id: connection-method
    attributes:
      label: System connection
      description: The device is physically connected to the host system using which connector?
      placeholder: e.g. PCI-E
    validations:
      required: true
  - type: input
    id: control-method
    attributes:
      label: System protocol
      description: The device uses which protocols to communicate with the host system?
      placeholder: e.g. HID, USB, I²C, SMBus 
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information about the device
      description: Include any useful additional information, such as USB vendor and product IDs, the output of `lsusb -v` (Linux) or `system_profiler SPUSBDataType` (Mac OS), links to external resources or already collected traffic data. 
      placeholder: |
        <!-- An example code block:
        ```
        $ libusb -v
        Bus 001 Device 007 ID 1e71:1714 NZXT Smart Device
        Device Descriptor [ ... ]
        ```
        -->
    validations:
      required: false
  - type: dropdown
    id: possible-support
    attributes:
      label: Can you help with the implementation or testing of the new device?
      description: Select as many options as apply, not manditory.
      multiple: true
      options:
        - testing changes on Linux
        - testing changes on Windows
        - testing changes on Mac OS
        - attempting to capture USB traffic 
        - attempting to capture I²C/SMBus traffic
        - analyzing traffic data
        - documenting the protocol
        - implementing the driver 
    validations:
      required: false