name: Other issue
description: Report other types of problems or request new features.
body:
  - type: checkboxes
    attributes:
      label: Is there already an issue for this?
      description: Please search our open issues to see if one already exists for this.
      options:
      - label: There is no open issue for this
        required: true
  - type: checkboxes
    attributes:
      label: Is this a request for support of a new device?
      description: We are not currently taking new device requests. Please send a pull request
        instead.
      options:
      - label: This is not a new device request
        required: true
  - type: checkboxes
    attributes:
      label: Is this a support request?
      description: Please use Discord for support requests.
      options:
      - label: This is not a support request
        required: true
  - type: textarea
    attributes:
      label: Description
      description: >
        Describe the issue or feature request as clearly as possible. You can use
        [Markdown](https://docs.github.com/en/get-started/writing-on-github).
    validations:
      required: true
